server:
  port: 8080

app:
  base-url: http://109.69.21.17:8080
  apk:
    storage-path: storage/apk
  icon:
    storage-path: storage/icons
  images:
    storage-path: storage/images

admin:
  login: admin
  password-hash: "$2b$10$arjMJZ3jBbuF9KRC4a9okud7F0aXjZqDm7/0UAxNoTP7ZWMkEhkzq"

jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/market
    username: market_user
    password: market_pass

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger
