[versions]
agp = "8.13.2"
kotlin = "2.0.21"

coreKtx = "1.17.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
leanback = "1.2.0"
lifecycleRuntimeKtx = "2.10.0"
material = "1.13.0"

filamentAndroid = "1.17.1"

retrofit = "2.11.0"
loggingInterceptor = "4.12.0"
kotlinxCoroutinesAndroid = "1.8.1"

glide = "4.16.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

material = { module = "com.google.android.material:material", version.ref = "material" }
filament-android = { module = "com.google.ar.sceneform:filament-android", version.ref = "filamentAndroid" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
